name: dns_test_selenium

on: workflow_dispatch

jobs:
  dns_ui_test:
    runs-on: windows-2019
    steps:
      - name: repo check-out
        uses: actions/checkout@v3
      
      - name: python install
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: chrome install
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 1090005
      
      - name: chrome version check
        run: chrome --version
      
      - name: python dependencies install
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      
      - name: tests run
        run: pytest --alluredir=allure-results test.py
        continue-on-error: true
        
      - name: get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ALLURE_DEPLOY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history        
          
        
